### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by HappyDay-design** [Ilhem23/change_lane_DQN#5]
Hello
Thank you very much

I run `python test.py`
Errors
Traceback (most recent call last):
  File "/home/osboxes/Desktop/change_lane_DQN/test.py", line 6, in <module>
    env = gym.make('gym_sumo-v0')
  File "/home/osboxes/anaconda3/envs/TF2/lib/python3.7/site-packages/gym/envs/registration.py", line 669, in make
    env = PassiveEnvChecker(env)
  File "/home/osboxes/anaconda3/envs/TF2/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 22, in __init__
    ), "The environment must specify an action space. https://www.gymlibrary.dev/content/environment_creation/"
AssertionError: The environment must specify an action space. https://www.gymlibrary.dev/content/environment_creation/

**Comment by HappyDay-design** [comment]
This model requires GPU to train.
In the past, I used CPU to train so It had errors
